language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install .
# command to run tests
script: py.test --cov astprint
after_success:
  coveralls
